window.translations = {
  'Gallery_Hover_Download_FreeImages_Text': 'Użytkownicy będą mogli pobrać tylko Twoje oryginalne obrazy ( nie darmowe obrazy Wix).',
  'Gallery_ArtStore_User_ProviderDown_Message': 'Niestety, wystąpił problem techniczny i sklep Art Store nie mógł być załadowany. Kliknij odśwież lub spróbuj ponownie później.',
  'Gallery_ArtStore_Organize_Images_EmptyState_Get_Started': 'Zacznij',
  'Gallery_Sharing_Disabled_In_Editor': 'Idź do swojej Opublikowanej witryny, aby to wypróbować i udostępnij swoje zdjęcia.',
  'Gallery _CartView_Cart_Label': 'Koszyk',
  'Gallery_ArtStore_Cart_Settings_Design_Font_Style_Label': 'Styl Czcionki i Kolor',
  'Gallery_ArtStore_UOU_TermsOfUse_Label': 'Regulamin',
  'Gallery_Empty_Description2': 'Kliknij Zarządzaj Mediami, aby rozpocząć',
  'Gallery_ArtStore_Cart_Settings_Design_Menu_Main_Label': 'Main',
  'Gallery_ArtStore_UoU_ProviderDown_Message': 'Przepraszamy, ale doświadczamy problemów technicznych. Odśwież stronę lub spróbuj ponownie później.',
  'Gallery_Empty_Title2': 'Niekonwencjonalna Galeria',
  'Gallery_ArtStore_Cart_Settings_Design_Font_Style_Tooltip_Title': 'Customize Font Style',
  'Gallery_ArtStore_ExpandMode_User_Message_Upload_Images': 'Możesz sprzedawać tylko swoje zdjęcia. Aby przesłać własne, przejdź do opcji "Zarządzaj Mediami".',
  'Gallery_ArtStore_UOU_Add_To_Cart_Button': 'Dodaj do Koszyka',
  'Gallery_ArtStore_Cart_Settings_Design_Select_Layout_Label': 'Select Layout',
  'Gallery_ArtStore_Organize_Images_EmptyState_Header': 'Czas Zacząć Tworzyć',
  'Gallery_ArtStore_Organize_Images_EmptyState_Text': 'Zacznij od dodania wysokiej jakości zdjęć',
  'Gallery_ArtStore_UOU_Select_License_Label': 'Select License',
  'Gallery_ArtStore_Cart_Settings_Design_Button_Default_Text': 'Cart',
  'Gallery_Empty_Title': 'Twoja Zachwycająca,',
  'Gallery_UOU_No_Online_Payment_Screen_Text': 'Zamówienie tych elementów nie jest teraz możliwe. Skontaktuj się z nami, aby sfinalizować zakupy.',
  'Gallery_Item_DefaultTitle_Long_Label': 'Nadaj swojemu elementowi unikalny tytuł.',
  'Gallery_ArtStore_Cart_Settings_Design_Menu_Design_Label': 'Design',
  'Gallery_ArtStore_Cart_Settings_Main_Button': 'Customize Icon',
  'Gallery_Item_DefaultDescription_Long_Label': 'Dodaj opis do swojego elementu, dzięki czemu odwiedzający będą mogli poznać historię obrazu lub wideo. Powiedz im o tym, gdzie zostało zrobione, jakiego rodzaju sprzętu użyłeś i o okolicznościach powstania.',
  'Gallery_ArtStore_Cart_Settings_Main_Text': 'Customize your mini cart with a different style and color',
  'Gallery_User_Set_Payment_Screen_Text': 'Odwiedzający nie mogą dokonać zakupu, ponieważ jeszcze nie skonfigurowałeś metody płatności. Aby skonfigurować metodę płatności, przejdź do zakładki Sklep i kliknij przycisk "Pobierz Należność".',
  'Gallery_Item_DefaultLink_Label': 'Sprawdź Wix.com',
  'Gallery_Item_DefaultTitle_Short_Label': 'Add a catchy title',
  'Gallery_OnStage_UoU_BuyNow_Label': 'Kup Teraz',
  'Gallery_ArtStore_Cart_Settings_Design_Font_Style_Tooltip_Text': 'Choose from a variety of font styles and colors to customize the look & feel of your cart.',
  'Gallery_Item_DefaultDescription_Short_Label': 'Tell your visitors a little about your item.',
  'Gallery_User_Set_Payment_Screen_Ok_Button': 'OK',
  'Gallery_User_Set_Payment_Screen_Header': 'Skonfiguruj metodę płatności, aby rozpocząć sprzedaż',
  'Gallery_ArtStore_Cart_Settings_Design_Button_Text_Label': 'Button Text',
  'Gallery_ArtStore_UOU_Continue_Checkout_Label': 'Przejdź do kasy',
  'Gallery_OnStage_UoU_ImageTitle_Label': 'Tytuł Obrazu',
  'Gallery_OnStage_UoU_Welcome_Text': 'Witaj w moim sklepie Art Store. Kliknij na Obraz, aby go kupić.',
  'Gallery_Empty_Description': 'Zacznij od dodania świetnych obrazów, filmów i tekstu.',
  'Gallery_Read_Less': 'Read Less',
  'Gallery_UOU_No_Online_Payment_Screen_Ok_Button': 'OK',
  'Gallery_ArtStore_Cart_Settings_Design_Icon_Color_Label': 'Icon Color',
  'Gallery_ArtStore_Organize_Images_EmptyState_Header2': 'Twój Piękny Art Store',
  'Gallery_Read_More': 'Czytaj dalej'
}